/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AddressCountryModel;
import io.swagger.client.model.PlayerRankingLevel;

/**
 * EntityProfileModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class EntityProfileModel {
  @SerializedName("GenerationTicks")
  private Long generationTicks = null;

  @SerializedName("Nickname")
  private String nickname = null;

  @SerializedName("LanModeEnabled")
  private Boolean lanModeEnabled = null;

  @SerializedName("LanSeatLocation")
  private String lanSeatLocation = null;

  @SerializedName("ArenaRankingLevel")
  private PlayerRankingLevel arenaRankingLevel = null;

  @SerializedName("EntityName")
  private String entityName = null;

  @SerializedName("EntityIsTeam")
  private Boolean entityIsTeam = null;

  @SerializedName("DisplayName")
  private String displayName = null;

  @SerializedName("Country")
  private AddressCountryModel country = null;

  @SerializedName("LogoUploaded")
  private Boolean logoUploaded = null;

  @SerializedName("LogoUrl")
  private String logoUrl = null;

  @SerializedName("LogoLastModified")
  private Double logoLastModified = null;

  @SerializedName("BackgroundUploaded")
  private Boolean backgroundUploaded = null;

  @SerializedName("BackgroundUrl")
  private String backgroundUrl = null;

  @SerializedName("BackgroundThumbnailUrl")
  private String backgroundThumbnailUrl = null;

  @SerializedName("BackgroundLastModified")
  private Double backgroundLastModified = null;

  @SerializedName("EntityMembershipId")
  private String entityMembershipId = null;

  public EntityProfileModel generationTicks(Long generationTicks) {
    this.generationTicks = generationTicks;
    return this;
  }

   /**
   * Get generationTicks
   * @return generationTicks
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getGenerationTicks() {
    return generationTicks;
  }

  public void setGenerationTicks(Long generationTicks) {
    this.generationTicks = generationTicks;
  }

  public EntityProfileModel nickname(String nickname) {
    this.nickname = nickname;
    return this;
  }

   /**
   * Get nickname
   * @return nickname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getNickname() {
    return nickname;
  }

  public void setNickname(String nickname) {
    this.nickname = nickname;
  }

  public EntityProfileModel lanModeEnabled(Boolean lanModeEnabled) {
    this.lanModeEnabled = lanModeEnabled;
    return this;
  }

   /**
   * Get lanModeEnabled
   * @return lanModeEnabled
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getLanModeEnabled() {
    return lanModeEnabled;
  }

  public void setLanModeEnabled(Boolean lanModeEnabled) {
    this.lanModeEnabled = lanModeEnabled;
  }

  public EntityProfileModel lanSeatLocation(String lanSeatLocation) {
    this.lanSeatLocation = lanSeatLocation;
    return this;
  }

   /**
   * Get lanSeatLocation
   * @return lanSeatLocation
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLanSeatLocation() {
    return lanSeatLocation;
  }

  public void setLanSeatLocation(String lanSeatLocation) {
    this.lanSeatLocation = lanSeatLocation;
  }

  public EntityProfileModel arenaRankingLevel(PlayerRankingLevel arenaRankingLevel) {
    this.arenaRankingLevel = arenaRankingLevel;
    return this;
  }

   /**
   * Get arenaRankingLevel
   * @return arenaRankingLevel
  **/
  @ApiModelProperty(example = "null", value = "")
  public PlayerRankingLevel getArenaRankingLevel() {
    return arenaRankingLevel;
  }

  public void setArenaRankingLevel(PlayerRankingLevel arenaRankingLevel) {
    this.arenaRankingLevel = arenaRankingLevel;
  }

  public EntityProfileModel entityName(String entityName) {
    this.entityName = entityName;
    return this;
  }

   /**
   * Get entityName
   * @return entityName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEntityName() {
    return entityName;
  }

  public void setEntityName(String entityName) {
    this.entityName = entityName;
  }

  public EntityProfileModel entityIsTeam(Boolean entityIsTeam) {
    this.entityIsTeam = entityIsTeam;
    return this;
  }

   /**
   * Get entityIsTeam
   * @return entityIsTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getEntityIsTeam() {
    return entityIsTeam;
  }

  public void setEntityIsTeam(Boolean entityIsTeam) {
    this.entityIsTeam = entityIsTeam;
  }

  public EntityProfileModel displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public EntityProfileModel country(AddressCountryModel country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(example = "null", value = "")
  public AddressCountryModel getCountry() {
    return country;
  }

  public void setCountry(AddressCountryModel country) {
    this.country = country;
  }

  public EntityProfileModel logoUploaded(Boolean logoUploaded) {
    this.logoUploaded = logoUploaded;
    return this;
  }

   /**
   * Get logoUploaded
   * @return logoUploaded
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getLogoUploaded() {
    return logoUploaded;
  }

  public void setLogoUploaded(Boolean logoUploaded) {
    this.logoUploaded = logoUploaded;
  }

  public EntityProfileModel logoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
    return this;
  }

   /**
   * Get logoUrl
   * @return logoUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLogoUrl() {
    return logoUrl;
  }

  public void setLogoUrl(String logoUrl) {
    this.logoUrl = logoUrl;
  }

  public EntityProfileModel logoLastModified(Double logoLastModified) {
    this.logoLastModified = logoLastModified;
    return this;
  }

   /**
   * Get logoLastModified
   * @return logoLastModified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getLogoLastModified() {
    return logoLastModified;
  }

  public void setLogoLastModified(Double logoLastModified) {
    this.logoLastModified = logoLastModified;
  }

  public EntityProfileModel backgroundUploaded(Boolean backgroundUploaded) {
    this.backgroundUploaded = backgroundUploaded;
    return this;
  }

   /**
   * Get backgroundUploaded
   * @return backgroundUploaded
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getBackgroundUploaded() {
    return backgroundUploaded;
  }

  public void setBackgroundUploaded(Boolean backgroundUploaded) {
    this.backgroundUploaded = backgroundUploaded;
  }

  public EntityProfileModel backgroundUrl(String backgroundUrl) {
    this.backgroundUrl = backgroundUrl;
    return this;
  }

   /**
   * Get backgroundUrl
   * @return backgroundUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBackgroundUrl() {
    return backgroundUrl;
  }

  public void setBackgroundUrl(String backgroundUrl) {
    this.backgroundUrl = backgroundUrl;
  }

  public EntityProfileModel backgroundThumbnailUrl(String backgroundThumbnailUrl) {
    this.backgroundThumbnailUrl = backgroundThumbnailUrl;
    return this;
  }

   /**
   * Get backgroundThumbnailUrl
   * @return backgroundThumbnailUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBackgroundThumbnailUrl() {
    return backgroundThumbnailUrl;
  }

  public void setBackgroundThumbnailUrl(String backgroundThumbnailUrl) {
    this.backgroundThumbnailUrl = backgroundThumbnailUrl;
  }

  public EntityProfileModel backgroundLastModified(Double backgroundLastModified) {
    this.backgroundLastModified = backgroundLastModified;
    return this;
  }

   /**
   * Get backgroundLastModified
   * @return backgroundLastModified
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getBackgroundLastModified() {
    return backgroundLastModified;
  }

  public void setBackgroundLastModified(Double backgroundLastModified) {
    this.backgroundLastModified = backgroundLastModified;
  }

  public EntityProfileModel entityMembershipId(String entityMembershipId) {
    this.entityMembershipId = entityMembershipId;
    return this;
  }

   /**
   * Get entityMembershipId
   * @return entityMembershipId
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEntityMembershipId() {
    return entityMembershipId;
  }

  public void setEntityMembershipId(String entityMembershipId) {
    this.entityMembershipId = entityMembershipId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityProfileModel entityProfileModel = (EntityProfileModel) o;
    return Objects.equals(this.generationTicks, entityProfileModel.generationTicks) &&
        Objects.equals(this.nickname, entityProfileModel.nickname) &&
        Objects.equals(this.lanModeEnabled, entityProfileModel.lanModeEnabled) &&
        Objects.equals(this.lanSeatLocation, entityProfileModel.lanSeatLocation) &&
        Objects.equals(this.arenaRankingLevel, entityProfileModel.arenaRankingLevel) &&
        Objects.equals(this.entityName, entityProfileModel.entityName) &&
        Objects.equals(this.entityIsTeam, entityProfileModel.entityIsTeam) &&
        Objects.equals(this.displayName, entityProfileModel.displayName) &&
        Objects.equals(this.country, entityProfileModel.country) &&
        Objects.equals(this.logoUploaded, entityProfileModel.logoUploaded) &&
        Objects.equals(this.logoUrl, entityProfileModel.logoUrl) &&
        Objects.equals(this.logoLastModified, entityProfileModel.logoLastModified) &&
        Objects.equals(this.backgroundUploaded, entityProfileModel.backgroundUploaded) &&
        Objects.equals(this.backgroundUrl, entityProfileModel.backgroundUrl) &&
        Objects.equals(this.backgroundThumbnailUrl, entityProfileModel.backgroundThumbnailUrl) &&
        Objects.equals(this.backgroundLastModified, entityProfileModel.backgroundLastModified) &&
        Objects.equals(this.entityMembershipId, entityProfileModel.entityMembershipId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(generationTicks, nickname, lanModeEnabled, lanSeatLocation, arenaRankingLevel, entityName, entityIsTeam, displayName, country, logoUploaded, logoUrl, logoLastModified, backgroundUploaded, backgroundUrl, backgroundThumbnailUrl, backgroundLastModified, entityMembershipId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityProfileModel {\n");
    
    sb.append("    generationTicks: ").append(toIndentedString(generationTicks)).append("\n");
    sb.append("    nickname: ").append(toIndentedString(nickname)).append("\n");
    sb.append("    lanModeEnabled: ").append(toIndentedString(lanModeEnabled)).append("\n");
    sb.append("    lanSeatLocation: ").append(toIndentedString(lanSeatLocation)).append("\n");
    sb.append("    arenaRankingLevel: ").append(toIndentedString(arenaRankingLevel)).append("\n");
    sb.append("    entityName: ").append(toIndentedString(entityName)).append("\n");
    sb.append("    entityIsTeam: ").append(toIndentedString(entityIsTeam)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    logoUploaded: ").append(toIndentedString(logoUploaded)).append("\n");
    sb.append("    logoUrl: ").append(toIndentedString(logoUrl)).append("\n");
    sb.append("    logoLastModified: ").append(toIndentedString(logoLastModified)).append("\n");
    sb.append("    backgroundUploaded: ").append(toIndentedString(backgroundUploaded)).append("\n");
    sb.append("    backgroundUrl: ").append(toIndentedString(backgroundUrl)).append("\n");
    sb.append("    backgroundThumbnailUrl: ").append(toIndentedString(backgroundThumbnailUrl)).append("\n");
    sb.append("    backgroundLastModified: ").append(toIndentedString(backgroundLastModified)).append("\n");
    sb.append("    entityMembershipId: ").append(toIndentedString(entityMembershipId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

