/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GameTitleOutputModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class GameTitleOutputModel {
  @SerializedName("GameTitleId")
  private Integer gameTitleId = null;

  @SerializedName("GameGuid")
  private String gameGuid = null;

  @SerializedName("GameName")
  private String gameName = null;

  @SerializedName("GameShortCode")
  private String gameShortCode = null;

  @SerializedName("GameDescription")
  private String gameDescription = null;

  @SerializedName("TotalWinnings")
  private Double totalWinnings = null;

  @SerializedName("GameWebsite")
  private String gameWebsite = null;

  @SerializedName("GameDownloadLink")
  private String gameDownloadLink = null;

  @SerializedName("GameTitleValidationMethodTypeId")
  private Integer gameTitleValidationMethodTypeId = null;

  @SerializedName("GameTitleValidationMethodType")
  private String gameTitleValidationMethodType = null;

  @SerializedName("GameImageLargeUrl")
  private String gameImageLargeUrl = null;

  @SerializedName("GameImageSmallUrl")
  private String gameImageSmallUrl = null;

  @SerializedName("GameBackgroundUrl")
  private String gameBackgroundUrl = null;

  @SerializedName("GameImageLargeRelativeUrl")
  private String gameImageLargeRelativeUrl = null;

  @SerializedName("GameImageSmallRelativeUrl")
  private String gameImageSmallRelativeUrl = null;

  @SerializedName("GameBackgroundRelativeUrl")
  private String gameBackgroundRelativeUrl = null;

  @SerializedName("GameVersion")
  private String gameVersion = null;

  @SerializedName("GameVersionNeedsVerification")
  private Boolean gameVersionNeedsVerification = null;

  @SerializedName("IssueGamesServerToMatch")
  private Boolean issueGamesServerToMatch = null;

  @SerializedName("SpawnArenaDynamicServer")
  private Boolean spawnArenaDynamicServer = null;

  @SerializedName("GameTitleStateId")
  private Integer gameTitleStateId = null;

  @SerializedName("TournamentCount")
  private Integer tournamentCount = null;

  @SerializedName("GamePlatform")
  private String gamePlatform = null;

  public GameTitleOutputModel gameTitleId(Integer gameTitleId) {
    this.gameTitleId = gameTitleId;
    return this;
  }

   /**
   * Get gameTitleId
   * @return gameTitleId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGameTitleId() {
    return gameTitleId;
  }

  public void setGameTitleId(Integer gameTitleId) {
    this.gameTitleId = gameTitleId;
  }

  public GameTitleOutputModel gameGuid(String gameGuid) {
    this.gameGuid = gameGuid;
    return this;
  }

   /**
   * Get gameGuid
   * @return gameGuid
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameGuid() {
    return gameGuid;
  }

  public void setGameGuid(String gameGuid) {
    this.gameGuid = gameGuid;
  }

  public GameTitleOutputModel gameName(String gameName) {
    this.gameName = gameName;
    return this;
  }

   /**
   * Get gameName
   * @return gameName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameName() {
    return gameName;
  }

  public void setGameName(String gameName) {
    this.gameName = gameName;
  }

  public GameTitleOutputModel gameShortCode(String gameShortCode) {
    this.gameShortCode = gameShortCode;
    return this;
  }

   /**
   * Get gameShortCode
   * @return gameShortCode
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameShortCode() {
    return gameShortCode;
  }

  public void setGameShortCode(String gameShortCode) {
    this.gameShortCode = gameShortCode;
  }

  public GameTitleOutputModel gameDescription(String gameDescription) {
    this.gameDescription = gameDescription;
    return this;
  }

   /**
   * Get gameDescription
   * @return gameDescription
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameDescription() {
    return gameDescription;
  }

  public void setGameDescription(String gameDescription) {
    this.gameDescription = gameDescription;
  }

  public GameTitleOutputModel totalWinnings(Double totalWinnings) {
    this.totalWinnings = totalWinnings;
    return this;
  }

   /**
   * Get totalWinnings
   * @return totalWinnings
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTotalWinnings() {
    return totalWinnings;
  }

  public void setTotalWinnings(Double totalWinnings) {
    this.totalWinnings = totalWinnings;
  }

  public GameTitleOutputModel gameWebsite(String gameWebsite) {
    this.gameWebsite = gameWebsite;
    return this;
  }

   /**
   * Get gameWebsite
   * @return gameWebsite
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameWebsite() {
    return gameWebsite;
  }

  public void setGameWebsite(String gameWebsite) {
    this.gameWebsite = gameWebsite;
  }

  public GameTitleOutputModel gameDownloadLink(String gameDownloadLink) {
    this.gameDownloadLink = gameDownloadLink;
    return this;
  }

   /**
   * Get gameDownloadLink
   * @return gameDownloadLink
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameDownloadLink() {
    return gameDownloadLink;
  }

  public void setGameDownloadLink(String gameDownloadLink) {
    this.gameDownloadLink = gameDownloadLink;
  }

  public GameTitleOutputModel gameTitleValidationMethodTypeId(Integer gameTitleValidationMethodTypeId) {
    this.gameTitleValidationMethodTypeId = gameTitleValidationMethodTypeId;
    return this;
  }

   /**
   * Get gameTitleValidationMethodTypeId
   * @return gameTitleValidationMethodTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGameTitleValidationMethodTypeId() {
    return gameTitleValidationMethodTypeId;
  }

  public void setGameTitleValidationMethodTypeId(Integer gameTitleValidationMethodTypeId) {
    this.gameTitleValidationMethodTypeId = gameTitleValidationMethodTypeId;
  }

  public GameTitleOutputModel gameTitleValidationMethodType(String gameTitleValidationMethodType) {
    this.gameTitleValidationMethodType = gameTitleValidationMethodType;
    return this;
  }

   /**
   * Get gameTitleValidationMethodType
   * @return gameTitleValidationMethodType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameTitleValidationMethodType() {
    return gameTitleValidationMethodType;
  }

  public void setGameTitleValidationMethodType(String gameTitleValidationMethodType) {
    this.gameTitleValidationMethodType = gameTitleValidationMethodType;
  }

  public GameTitleOutputModel gameImageLargeUrl(String gameImageLargeUrl) {
    this.gameImageLargeUrl = gameImageLargeUrl;
    return this;
  }

   /**
   * Get gameImageLargeUrl
   * @return gameImageLargeUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameImageLargeUrl() {
    return gameImageLargeUrl;
  }

  public void setGameImageLargeUrl(String gameImageLargeUrl) {
    this.gameImageLargeUrl = gameImageLargeUrl;
  }

  public GameTitleOutputModel gameImageSmallUrl(String gameImageSmallUrl) {
    this.gameImageSmallUrl = gameImageSmallUrl;
    return this;
  }

   /**
   * Get gameImageSmallUrl
   * @return gameImageSmallUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameImageSmallUrl() {
    return gameImageSmallUrl;
  }

  public void setGameImageSmallUrl(String gameImageSmallUrl) {
    this.gameImageSmallUrl = gameImageSmallUrl;
  }

  public GameTitleOutputModel gameBackgroundUrl(String gameBackgroundUrl) {
    this.gameBackgroundUrl = gameBackgroundUrl;
    return this;
  }

   /**
   * Get gameBackgroundUrl
   * @return gameBackgroundUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameBackgroundUrl() {
    return gameBackgroundUrl;
  }

  public void setGameBackgroundUrl(String gameBackgroundUrl) {
    this.gameBackgroundUrl = gameBackgroundUrl;
  }

  public GameTitleOutputModel gameImageLargeRelativeUrl(String gameImageLargeRelativeUrl) {
    this.gameImageLargeRelativeUrl = gameImageLargeRelativeUrl;
    return this;
  }

   /**
   * Get gameImageLargeRelativeUrl
   * @return gameImageLargeRelativeUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameImageLargeRelativeUrl() {
    return gameImageLargeRelativeUrl;
  }

  public void setGameImageLargeRelativeUrl(String gameImageLargeRelativeUrl) {
    this.gameImageLargeRelativeUrl = gameImageLargeRelativeUrl;
  }

  public GameTitleOutputModel gameImageSmallRelativeUrl(String gameImageSmallRelativeUrl) {
    this.gameImageSmallRelativeUrl = gameImageSmallRelativeUrl;
    return this;
  }

   /**
   * Get gameImageSmallRelativeUrl
   * @return gameImageSmallRelativeUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameImageSmallRelativeUrl() {
    return gameImageSmallRelativeUrl;
  }

  public void setGameImageSmallRelativeUrl(String gameImageSmallRelativeUrl) {
    this.gameImageSmallRelativeUrl = gameImageSmallRelativeUrl;
  }

  public GameTitleOutputModel gameBackgroundRelativeUrl(String gameBackgroundRelativeUrl) {
    this.gameBackgroundRelativeUrl = gameBackgroundRelativeUrl;
    return this;
  }

   /**
   * Get gameBackgroundRelativeUrl
   * @return gameBackgroundRelativeUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameBackgroundRelativeUrl() {
    return gameBackgroundRelativeUrl;
  }

  public void setGameBackgroundRelativeUrl(String gameBackgroundRelativeUrl) {
    this.gameBackgroundRelativeUrl = gameBackgroundRelativeUrl;
  }

  public GameTitleOutputModel gameVersion(String gameVersion) {
    this.gameVersion = gameVersion;
    return this;
  }

   /**
   * Get gameVersion
   * @return gameVersion
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameVersion() {
    return gameVersion;
  }

  public void setGameVersion(String gameVersion) {
    this.gameVersion = gameVersion;
  }

  public GameTitleOutputModel gameVersionNeedsVerification(Boolean gameVersionNeedsVerification) {
    this.gameVersionNeedsVerification = gameVersionNeedsVerification;
    return this;
  }

   /**
   * Get gameVersionNeedsVerification
   * @return gameVersionNeedsVerification
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getGameVersionNeedsVerification() {
    return gameVersionNeedsVerification;
  }

  public void setGameVersionNeedsVerification(Boolean gameVersionNeedsVerification) {
    this.gameVersionNeedsVerification = gameVersionNeedsVerification;
  }

  public GameTitleOutputModel issueGamesServerToMatch(Boolean issueGamesServerToMatch) {
    this.issueGamesServerToMatch = issueGamesServerToMatch;
    return this;
  }

   /**
   * Get issueGamesServerToMatch
   * @return issueGamesServerToMatch
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIssueGamesServerToMatch() {
    return issueGamesServerToMatch;
  }

  public void setIssueGamesServerToMatch(Boolean issueGamesServerToMatch) {
    this.issueGamesServerToMatch = issueGamesServerToMatch;
  }

  public GameTitleOutputModel spawnArenaDynamicServer(Boolean spawnArenaDynamicServer) {
    this.spawnArenaDynamicServer = spawnArenaDynamicServer;
    return this;
  }

   /**
   * Get spawnArenaDynamicServer
   * @return spawnArenaDynamicServer
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getSpawnArenaDynamicServer() {
    return spawnArenaDynamicServer;
  }

  public void setSpawnArenaDynamicServer(Boolean spawnArenaDynamicServer) {
    this.spawnArenaDynamicServer = spawnArenaDynamicServer;
  }

  public GameTitleOutputModel gameTitleStateId(Integer gameTitleStateId) {
    this.gameTitleStateId = gameTitleStateId;
    return this;
  }

   /**
   * Get gameTitleStateId
   * @return gameTitleStateId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGameTitleStateId() {
    return gameTitleStateId;
  }

  public void setGameTitleStateId(Integer gameTitleStateId) {
    this.gameTitleStateId = gameTitleStateId;
  }

  public GameTitleOutputModel tournamentCount(Integer tournamentCount) {
    this.tournamentCount = tournamentCount;
    return this;
  }

   /**
   * Get tournamentCount
   * @return tournamentCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTournamentCount() {
    return tournamentCount;
  }

  public void setTournamentCount(Integer tournamentCount) {
    this.tournamentCount = tournamentCount;
  }

  public GameTitleOutputModel gamePlatform(String gamePlatform) {
    this.gamePlatform = gamePlatform;
    return this;
  }

   /**
   * Get gamePlatform
   * @return gamePlatform
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGamePlatform() {
    return gamePlatform;
  }

  public void setGamePlatform(String gamePlatform) {
    this.gamePlatform = gamePlatform;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameTitleOutputModel gameTitleOutputModel = (GameTitleOutputModel) o;
    return Objects.equals(this.gameTitleId, gameTitleOutputModel.gameTitleId) &&
        Objects.equals(this.gameGuid, gameTitleOutputModel.gameGuid) &&
        Objects.equals(this.gameName, gameTitleOutputModel.gameName) &&
        Objects.equals(this.gameShortCode, gameTitleOutputModel.gameShortCode) &&
        Objects.equals(this.gameDescription, gameTitleOutputModel.gameDescription) &&
        Objects.equals(this.totalWinnings, gameTitleOutputModel.totalWinnings) &&
        Objects.equals(this.gameWebsite, gameTitleOutputModel.gameWebsite) &&
        Objects.equals(this.gameDownloadLink, gameTitleOutputModel.gameDownloadLink) &&
        Objects.equals(this.gameTitleValidationMethodTypeId, gameTitleOutputModel.gameTitleValidationMethodTypeId) &&
        Objects.equals(this.gameTitleValidationMethodType, gameTitleOutputModel.gameTitleValidationMethodType) &&
        Objects.equals(this.gameImageLargeUrl, gameTitleOutputModel.gameImageLargeUrl) &&
        Objects.equals(this.gameImageSmallUrl, gameTitleOutputModel.gameImageSmallUrl) &&
        Objects.equals(this.gameBackgroundUrl, gameTitleOutputModel.gameBackgroundUrl) &&
        Objects.equals(this.gameImageLargeRelativeUrl, gameTitleOutputModel.gameImageLargeRelativeUrl) &&
        Objects.equals(this.gameImageSmallRelativeUrl, gameTitleOutputModel.gameImageSmallRelativeUrl) &&
        Objects.equals(this.gameBackgroundRelativeUrl, gameTitleOutputModel.gameBackgroundRelativeUrl) &&
        Objects.equals(this.gameVersion, gameTitleOutputModel.gameVersion) &&
        Objects.equals(this.gameVersionNeedsVerification, gameTitleOutputModel.gameVersionNeedsVerification) &&
        Objects.equals(this.issueGamesServerToMatch, gameTitleOutputModel.issueGamesServerToMatch) &&
        Objects.equals(this.spawnArenaDynamicServer, gameTitleOutputModel.spawnArenaDynamicServer) &&
        Objects.equals(this.gameTitleStateId, gameTitleOutputModel.gameTitleStateId) &&
        Objects.equals(this.tournamentCount, gameTitleOutputModel.tournamentCount) &&
        Objects.equals(this.gamePlatform, gameTitleOutputModel.gamePlatform);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gameTitleId, gameGuid, gameName, gameShortCode, gameDescription, totalWinnings, gameWebsite, gameDownloadLink, gameTitleValidationMethodTypeId, gameTitleValidationMethodType, gameImageLargeUrl, gameImageSmallUrl, gameBackgroundUrl, gameImageLargeRelativeUrl, gameImageSmallRelativeUrl, gameBackgroundRelativeUrl, gameVersion, gameVersionNeedsVerification, issueGamesServerToMatch, spawnArenaDynamicServer, gameTitleStateId, tournamentCount, gamePlatform);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameTitleOutputModel {\n");
    
    sb.append("    gameTitleId: ").append(toIndentedString(gameTitleId)).append("\n");
    sb.append("    gameGuid: ").append(toIndentedString(gameGuid)).append("\n");
    sb.append("    gameName: ").append(toIndentedString(gameName)).append("\n");
    sb.append("    gameShortCode: ").append(toIndentedString(gameShortCode)).append("\n");
    sb.append("    gameDescription: ").append(toIndentedString(gameDescription)).append("\n");
    sb.append("    totalWinnings: ").append(toIndentedString(totalWinnings)).append("\n");
    sb.append("    gameWebsite: ").append(toIndentedString(gameWebsite)).append("\n");
    sb.append("    gameDownloadLink: ").append(toIndentedString(gameDownloadLink)).append("\n");
    sb.append("    gameTitleValidationMethodTypeId: ").append(toIndentedString(gameTitleValidationMethodTypeId)).append("\n");
    sb.append("    gameTitleValidationMethodType: ").append(toIndentedString(gameTitleValidationMethodType)).append("\n");
    sb.append("    gameImageLargeUrl: ").append(toIndentedString(gameImageLargeUrl)).append("\n");
    sb.append("    gameImageSmallUrl: ").append(toIndentedString(gameImageSmallUrl)).append("\n");
    sb.append("    gameBackgroundUrl: ").append(toIndentedString(gameBackgroundUrl)).append("\n");
    sb.append("    gameImageLargeRelativeUrl: ").append(toIndentedString(gameImageLargeRelativeUrl)).append("\n");
    sb.append("    gameImageSmallRelativeUrl: ").append(toIndentedString(gameImageSmallRelativeUrl)).append("\n");
    sb.append("    gameBackgroundRelativeUrl: ").append(toIndentedString(gameBackgroundRelativeUrl)).append("\n");
    sb.append("    gameVersion: ").append(toIndentedString(gameVersion)).append("\n");
    sb.append("    gameVersionNeedsVerification: ").append(toIndentedString(gameVersionNeedsVerification)).append("\n");
    sb.append("    issueGamesServerToMatch: ").append(toIndentedString(issueGamesServerToMatch)).append("\n");
    sb.append("    spawnArenaDynamicServer: ").append(toIndentedString(spawnArenaDynamicServer)).append("\n");
    sb.append("    gameTitleStateId: ").append(toIndentedString(gameTitleStateId)).append("\n");
    sb.append("    tournamentCount: ").append(toIndentedString(tournamentCount)).append("\n");
    sb.append("    gamePlatform: ").append(toIndentedString(gamePlatform)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

