/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GameTitleStatisticMvpModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class GameTitleStatisticMvpModel {
  @SerializedName("GameTitleStatisticMvpId")
  private Long gameTitleStatisticMvpId = null;

  @SerializedName("GameTitleId")
  private Integer gameTitleId = null;

  @SerializedName("DisplayOrder")
  private Integer displayOrder = null;

  @SerializedName("StatisticKeyName")
  private String statisticKeyName = null;

  @SerializedName("ValueOrdering")
  private String valueOrdering = null;

  @SerializedName("MvpFriendlyName")
  private String mvpFriendlyName = null;

  @SerializedName("MvpImageUrl")
  private String mvpImageUrl = null;

  public GameTitleStatisticMvpModel gameTitleStatisticMvpId(Long gameTitleStatisticMvpId) {
    this.gameTitleStatisticMvpId = gameTitleStatisticMvpId;
    return this;
  }

   /**
   * Get gameTitleStatisticMvpId
   * @return gameTitleStatisticMvpId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getGameTitleStatisticMvpId() {
    return gameTitleStatisticMvpId;
  }

  public void setGameTitleStatisticMvpId(Long gameTitleStatisticMvpId) {
    this.gameTitleStatisticMvpId = gameTitleStatisticMvpId;
  }

  public GameTitleStatisticMvpModel gameTitleId(Integer gameTitleId) {
    this.gameTitleId = gameTitleId;
    return this;
  }

   /**
   * Get gameTitleId
   * @return gameTitleId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGameTitleId() {
    return gameTitleId;
  }

  public void setGameTitleId(Integer gameTitleId) {
    this.gameTitleId = gameTitleId;
  }

  public GameTitleStatisticMvpModel displayOrder(Integer displayOrder) {
    this.displayOrder = displayOrder;
    return this;
  }

   /**
   * Get displayOrder
   * @return displayOrder
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDisplayOrder() {
    return displayOrder;
  }

  public void setDisplayOrder(Integer displayOrder) {
    this.displayOrder = displayOrder;
  }

  public GameTitleStatisticMvpModel statisticKeyName(String statisticKeyName) {
    this.statisticKeyName = statisticKeyName;
    return this;
  }

   /**
   * Get statisticKeyName
   * @return statisticKeyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getStatisticKeyName() {
    return statisticKeyName;
  }

  public void setStatisticKeyName(String statisticKeyName) {
    this.statisticKeyName = statisticKeyName;
  }

  public GameTitleStatisticMvpModel valueOrdering(String valueOrdering) {
    this.valueOrdering = valueOrdering;
    return this;
  }

   /**
   * Get valueOrdering
   * @return valueOrdering
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValueOrdering() {
    return valueOrdering;
  }

  public void setValueOrdering(String valueOrdering) {
    this.valueOrdering = valueOrdering;
  }

  public GameTitleStatisticMvpModel mvpFriendlyName(String mvpFriendlyName) {
    this.mvpFriendlyName = mvpFriendlyName;
    return this;
  }

   /**
   * Get mvpFriendlyName
   * @return mvpFriendlyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMvpFriendlyName() {
    return mvpFriendlyName;
  }

  public void setMvpFriendlyName(String mvpFriendlyName) {
    this.mvpFriendlyName = mvpFriendlyName;
  }

  public GameTitleStatisticMvpModel mvpImageUrl(String mvpImageUrl) {
    this.mvpImageUrl = mvpImageUrl;
    return this;
  }

   /**
   * Get mvpImageUrl
   * @return mvpImageUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getMvpImageUrl() {
    return mvpImageUrl;
  }

  public void setMvpImageUrl(String mvpImageUrl) {
    this.mvpImageUrl = mvpImageUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameTitleStatisticMvpModel gameTitleStatisticMvpModel = (GameTitleStatisticMvpModel) o;
    return Objects.equals(this.gameTitleStatisticMvpId, gameTitleStatisticMvpModel.gameTitleStatisticMvpId) &&
        Objects.equals(this.gameTitleId, gameTitleStatisticMvpModel.gameTitleId) &&
        Objects.equals(this.displayOrder, gameTitleStatisticMvpModel.displayOrder) &&
        Objects.equals(this.statisticKeyName, gameTitleStatisticMvpModel.statisticKeyName) &&
        Objects.equals(this.valueOrdering, gameTitleStatisticMvpModel.valueOrdering) &&
        Objects.equals(this.mvpFriendlyName, gameTitleStatisticMvpModel.mvpFriendlyName) &&
        Objects.equals(this.mvpImageUrl, gameTitleStatisticMvpModel.mvpImageUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gameTitleStatisticMvpId, gameTitleId, displayOrder, statisticKeyName, valueOrdering, mvpFriendlyName, mvpImageUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameTitleStatisticMvpModel {\n");
    
    sb.append("    gameTitleStatisticMvpId: ").append(toIndentedString(gameTitleStatisticMvpId)).append("\n");
    sb.append("    gameTitleId: ").append(toIndentedString(gameTitleId)).append("\n");
    sb.append("    displayOrder: ").append(toIndentedString(displayOrder)).append("\n");
    sb.append("    statisticKeyName: ").append(toIndentedString(statisticKeyName)).append("\n");
    sb.append("    valueOrdering: ").append(toIndentedString(valueOrdering)).append("\n");
    sb.append("    mvpFriendlyName: ").append(toIndentedString(mvpFriendlyName)).append("\n");
    sb.append("    mvpImageUrl: ").append(toIndentedString(mvpImageUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

