/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GameTitleMapNameModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class GameTitleMapNameModel {
  @SerializedName("GameTitleMapNameId")
  private Integer gameTitleMapNameId = null;

  @SerializedName("GameTitleId")
  private Integer gameTitleId = null;

  @SerializedName("GameTitleMapFileName")
  private String gameTitleMapFileName = null;

  @SerializedName("GameTitleMapProperName")
  private String gameTitleMapProperName = null;

  @SerializedName("GameTitleMapGroupName")
  private String gameTitleMapGroupName = null;

  @SerializedName("GameTitleMapImageUrlPartialPath")
  private String gameTitleMapImageUrlPartialPath = null;

  public GameTitleMapNameModel gameTitleMapNameId(Integer gameTitleMapNameId) {
    this.gameTitleMapNameId = gameTitleMapNameId;
    return this;
  }

   /**
   * Get gameTitleMapNameId
   * @return gameTitleMapNameId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGameTitleMapNameId() {
    return gameTitleMapNameId;
  }

  public void setGameTitleMapNameId(Integer gameTitleMapNameId) {
    this.gameTitleMapNameId = gameTitleMapNameId;
  }

  public GameTitleMapNameModel gameTitleId(Integer gameTitleId) {
    this.gameTitleId = gameTitleId;
    return this;
  }

   /**
   * Get gameTitleId
   * @return gameTitleId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGameTitleId() {
    return gameTitleId;
  }

  public void setGameTitleId(Integer gameTitleId) {
    this.gameTitleId = gameTitleId;
  }

  public GameTitleMapNameModel gameTitleMapFileName(String gameTitleMapFileName) {
    this.gameTitleMapFileName = gameTitleMapFileName;
    return this;
  }

   /**
   * Get gameTitleMapFileName
   * @return gameTitleMapFileName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameTitleMapFileName() {
    return gameTitleMapFileName;
  }

  public void setGameTitleMapFileName(String gameTitleMapFileName) {
    this.gameTitleMapFileName = gameTitleMapFileName;
  }

  public GameTitleMapNameModel gameTitleMapProperName(String gameTitleMapProperName) {
    this.gameTitleMapProperName = gameTitleMapProperName;
    return this;
  }

   /**
   * Get gameTitleMapProperName
   * @return gameTitleMapProperName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameTitleMapProperName() {
    return gameTitleMapProperName;
  }

  public void setGameTitleMapProperName(String gameTitleMapProperName) {
    this.gameTitleMapProperName = gameTitleMapProperName;
  }

  public GameTitleMapNameModel gameTitleMapGroupName(String gameTitleMapGroupName) {
    this.gameTitleMapGroupName = gameTitleMapGroupName;
    return this;
  }

   /**
   * Get gameTitleMapGroupName
   * @return gameTitleMapGroupName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameTitleMapGroupName() {
    return gameTitleMapGroupName;
  }

  public void setGameTitleMapGroupName(String gameTitleMapGroupName) {
    this.gameTitleMapGroupName = gameTitleMapGroupName;
  }

   /**
   * Get gameTitleMapImageUrlPartialPath
   * @return gameTitleMapImageUrlPartialPath
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameTitleMapImageUrlPartialPath() {
    return gameTitleMapImageUrlPartialPath;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameTitleMapNameModel gameTitleMapNameModel = (GameTitleMapNameModel) o;
    return Objects.equals(this.gameTitleMapNameId, gameTitleMapNameModel.gameTitleMapNameId) &&
        Objects.equals(this.gameTitleId, gameTitleMapNameModel.gameTitleId) &&
        Objects.equals(this.gameTitleMapFileName, gameTitleMapNameModel.gameTitleMapFileName) &&
        Objects.equals(this.gameTitleMapProperName, gameTitleMapNameModel.gameTitleMapProperName) &&
        Objects.equals(this.gameTitleMapGroupName, gameTitleMapNameModel.gameTitleMapGroupName) &&
        Objects.equals(this.gameTitleMapImageUrlPartialPath, gameTitleMapNameModel.gameTitleMapImageUrlPartialPath);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gameTitleMapNameId, gameTitleId, gameTitleMapFileName, gameTitleMapProperName, gameTitleMapGroupName, gameTitleMapImageUrlPartialPath);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameTitleMapNameModel {\n");
    
    sb.append("    gameTitleMapNameId: ").append(toIndentedString(gameTitleMapNameId)).append("\n");
    sb.append("    gameTitleId: ").append(toIndentedString(gameTitleId)).append("\n");
    sb.append("    gameTitleMapFileName: ").append(toIndentedString(gameTitleMapFileName)).append("\n");
    sb.append("    gameTitleMapProperName: ").append(toIndentedString(gameTitleMapProperName)).append("\n");
    sb.append("    gameTitleMapGroupName: ").append(toIndentedString(gameTitleMapGroupName)).append("\n");
    sb.append("    gameTitleMapImageUrlPartialPath: ").append(toIndentedString(gameTitleMapImageUrlPartialPath)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

