/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GameTitleCallbackTemplateModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class GameTitleCallbackTemplateModel {
  @SerializedName("GameTitleCallbackTemplateId")
  private Integer gameTitleCallbackTemplateId = null;

  @SerializedName("GameTitleCallbackTemplate")
  private String gameTitleCallbackTemplate = null;

  public GameTitleCallbackTemplateModel gameTitleCallbackTemplateId(Integer gameTitleCallbackTemplateId) {
    this.gameTitleCallbackTemplateId = gameTitleCallbackTemplateId;
    return this;
  }

   /**
   * Get gameTitleCallbackTemplateId
   * @return gameTitleCallbackTemplateId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGameTitleCallbackTemplateId() {
    return gameTitleCallbackTemplateId;
  }

  public void setGameTitleCallbackTemplateId(Integer gameTitleCallbackTemplateId) {
    this.gameTitleCallbackTemplateId = gameTitleCallbackTemplateId;
  }

  public GameTitleCallbackTemplateModel gameTitleCallbackTemplate(String gameTitleCallbackTemplate) {
    this.gameTitleCallbackTemplate = gameTitleCallbackTemplate;
    return this;
  }

   /**
   * Get gameTitleCallbackTemplate
   * @return gameTitleCallbackTemplate
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameTitleCallbackTemplate() {
    return gameTitleCallbackTemplate;
  }

  public void setGameTitleCallbackTemplate(String gameTitleCallbackTemplate) {
    this.gameTitleCallbackTemplate = gameTitleCallbackTemplate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameTitleCallbackTemplateModel gameTitleCallbackTemplateModel = (GameTitleCallbackTemplateModel) o;
    return Objects.equals(this.gameTitleCallbackTemplateId, gameTitleCallbackTemplateModel.gameTitleCallbackTemplateId) &&
        Objects.equals(this.gameTitleCallbackTemplate, gameTitleCallbackTemplateModel.gameTitleCallbackTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gameTitleCallbackTemplateId, gameTitleCallbackTemplate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameTitleCallbackTemplateModel {\n");
    
    sb.append("    gameTitleCallbackTemplateId: ").append(toIndentedString(gameTitleCallbackTemplateId)).append("\n");
    sb.append("    gameTitleCallbackTemplate: ").append(toIndentedString(gameTitleCallbackTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

