/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GameTitleStatisticModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class GameTitleStatisticModel {
  @SerializedName("GameTitleId")
  private Integer gameTitleId = null;

  @SerializedName("DisplayOrder")
  private Integer displayOrder = null;

  @SerializedName("IsCumulative")
  private Boolean isCumulative = null;

  @SerializedName("IsPercentage")
  private Boolean isPercentage = null;

  @SerializedName("FriendlyName")
  private String friendlyName = null;

  @SerializedName("KeyName")
  private String keyName = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("Category")
  private String category = null;

  @SerializedName("SubCategory")
  private String subCategory = null;

  @SerializedName("ValueOrdering")
  private String valueOrdering = null;

  public GameTitleStatisticModel gameTitleId(Integer gameTitleId) {
    this.gameTitleId = gameTitleId;
    return this;
  }

   /**
   * Get gameTitleId
   * @return gameTitleId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGameTitleId() {
    return gameTitleId;
  }

  public void setGameTitleId(Integer gameTitleId) {
    this.gameTitleId = gameTitleId;
  }

  public GameTitleStatisticModel displayOrder(Integer displayOrder) {
    this.displayOrder = displayOrder;
    return this;
  }

   /**
   * Get displayOrder
   * @return displayOrder
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getDisplayOrder() {
    return displayOrder;
  }

  public void setDisplayOrder(Integer displayOrder) {
    this.displayOrder = displayOrder;
  }

  public GameTitleStatisticModel isCumulative(Boolean isCumulative) {
    this.isCumulative = isCumulative;
    return this;
  }

   /**
   * Get isCumulative
   * @return isCumulative
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsCumulative() {
    return isCumulative;
  }

  public void setIsCumulative(Boolean isCumulative) {
    this.isCumulative = isCumulative;
  }

  public GameTitleStatisticModel isPercentage(Boolean isPercentage) {
    this.isPercentage = isPercentage;
    return this;
  }

   /**
   * Get isPercentage
   * @return isPercentage
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsPercentage() {
    return isPercentage;
  }

  public void setIsPercentage(Boolean isPercentage) {
    this.isPercentage = isPercentage;
  }

  public GameTitleStatisticModel friendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
    return this;
  }

   /**
   * Get friendlyName
   * @return friendlyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getFriendlyName() {
    return friendlyName;
  }

  public void setFriendlyName(String friendlyName) {
    this.friendlyName = friendlyName;
  }

  public GameTitleStatisticModel keyName(String keyName) {
    this.keyName = keyName;
    return this;
  }

   /**
   * Get keyName
   * @return keyName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getKeyName() {
    return keyName;
  }

  public void setKeyName(String keyName) {
    this.keyName = keyName;
  }

  public GameTitleStatisticModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public GameTitleStatisticModel category(String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getCategory() {
    return category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public GameTitleStatisticModel subCategory(String subCategory) {
    this.subCategory = subCategory;
    return this;
  }

   /**
   * Get subCategory
   * @return subCategory
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getSubCategory() {
    return subCategory;
  }

  public void setSubCategory(String subCategory) {
    this.subCategory = subCategory;
  }

  public GameTitleStatisticModel valueOrdering(String valueOrdering) {
    this.valueOrdering = valueOrdering;
    return this;
  }

   /**
   * Get valueOrdering
   * @return valueOrdering
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getValueOrdering() {
    return valueOrdering;
  }

  public void setValueOrdering(String valueOrdering) {
    this.valueOrdering = valueOrdering;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GameTitleStatisticModel gameTitleStatisticModel = (GameTitleStatisticModel) o;
    return Objects.equals(this.gameTitleId, gameTitleStatisticModel.gameTitleId) &&
        Objects.equals(this.displayOrder, gameTitleStatisticModel.displayOrder) &&
        Objects.equals(this.isCumulative, gameTitleStatisticModel.isCumulative) &&
        Objects.equals(this.isPercentage, gameTitleStatisticModel.isPercentage) &&
        Objects.equals(this.friendlyName, gameTitleStatisticModel.friendlyName) &&
        Objects.equals(this.keyName, gameTitleStatisticModel.keyName) &&
        Objects.equals(this.description, gameTitleStatisticModel.description) &&
        Objects.equals(this.category, gameTitleStatisticModel.category) &&
        Objects.equals(this.subCategory, gameTitleStatisticModel.subCategory) &&
        Objects.equals(this.valueOrdering, gameTitleStatisticModel.valueOrdering);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gameTitleId, displayOrder, isCumulative, isPercentage, friendlyName, keyName, description, category, subCategory, valueOrdering);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GameTitleStatisticModel {\n");
    
    sb.append("    gameTitleId: ").append(toIndentedString(gameTitleId)).append("\n");
    sb.append("    displayOrder: ").append(toIndentedString(displayOrder)).append("\n");
    sb.append("    isCumulative: ").append(toIndentedString(isCumulative)).append("\n");
    sb.append("    isPercentage: ").append(toIndentedString(isPercentage)).append("\n");
    sb.append("    friendlyName: ").append(toIndentedString(friendlyName)).append("\n");
    sb.append("    keyName: ").append(toIndentedString(keyName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    subCategory: ").append(toIndentedString(subCategory)).append("\n");
    sb.append("    valueOrdering: ").append(toIndentedString(valueOrdering)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

