/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * GamingServerRegionModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class GamingServerRegionModel {
  @SerializedName("GamingServerRegionId")
  private Integer gamingServerRegionId = null;

  @SerializedName("GamingServerRegionName")
  private String gamingServerRegionName = null;

  public GamingServerRegionModel gamingServerRegionId(Integer gamingServerRegionId) {
    this.gamingServerRegionId = gamingServerRegionId;
    return this;
  }

   /**
   * Get gamingServerRegionId
   * @return gamingServerRegionId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGamingServerRegionId() {
    return gamingServerRegionId;
  }

  public void setGamingServerRegionId(Integer gamingServerRegionId) {
    this.gamingServerRegionId = gamingServerRegionId;
  }

  public GamingServerRegionModel gamingServerRegionName(String gamingServerRegionName) {
    this.gamingServerRegionName = gamingServerRegionName;
    return this;
  }

   /**
   * Get gamingServerRegionName
   * @return gamingServerRegionName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGamingServerRegionName() {
    return gamingServerRegionName;
  }

  public void setGamingServerRegionName(String gamingServerRegionName) {
    this.gamingServerRegionName = gamingServerRegionName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GamingServerRegionModel gamingServerRegionModel = (GamingServerRegionModel) o;
    return Objects.equals(this.gamingServerRegionId, gamingServerRegionModel.gamingServerRegionId) &&
        Objects.equals(this.gamingServerRegionName, gamingServerRegionModel.gamingServerRegionName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(gamingServerRegionId, gamingServerRegionName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GamingServerRegionModel {\n");
    
    sb.append("    gamingServerRegionId: ").append(toIndentedString(gamingServerRegionId)).append("\n");
    sb.append("    gamingServerRegionName: ").append(toIndentedString(gamingServerRegionName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

