/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * InsiderPostModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class InsiderPostModel {
  @SerializedName("PostTitle")
  private String postTitle = null;

  @SerializedName("PostDateTime")
  private DateTime postDateTime = null;

  @SerializedName("InsiderUrl")
  private String insiderUrl = null;

  @SerializedName("AuthorName")
  private String authorName = null;

  @SerializedName("PostContent")
  private String postContent = null;

  @SerializedName("CommentsCount")
  private Integer commentsCount = null;

  public InsiderPostModel postTitle(String postTitle) {
    this.postTitle = postTitle;
    return this;
  }

   /**
   * Get postTitle
   * @return postTitle
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPostTitle() {
    return postTitle;
  }

  public void setPostTitle(String postTitle) {
    this.postTitle = postTitle;
  }

  public InsiderPostModel postDateTime(DateTime postDateTime) {
    this.postDateTime = postDateTime;
    return this;
  }

   /**
   * Get postDateTime
   * @return postDateTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getPostDateTime() {
    return postDateTime;
  }

  public void setPostDateTime(DateTime postDateTime) {
    this.postDateTime = postDateTime;
  }

  public InsiderPostModel insiderUrl(String insiderUrl) {
    this.insiderUrl = insiderUrl;
    return this;
  }

   /**
   * Get insiderUrl
   * @return insiderUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getInsiderUrl() {
    return insiderUrl;
  }

  public void setInsiderUrl(String insiderUrl) {
    this.insiderUrl = insiderUrl;
  }

  public InsiderPostModel authorName(String authorName) {
    this.authorName = authorName;
    return this;
  }

   /**
   * Get authorName
   * @return authorName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getAuthorName() {
    return authorName;
  }

  public void setAuthorName(String authorName) {
    this.authorName = authorName;
  }

  public InsiderPostModel postContent(String postContent) {
    this.postContent = postContent;
    return this;
  }

   /**
   * Get postContent
   * @return postContent
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getPostContent() {
    return postContent;
  }

  public void setPostContent(String postContent) {
    this.postContent = postContent;
  }

  public InsiderPostModel commentsCount(Integer commentsCount) {
    this.commentsCount = commentsCount;
    return this;
  }

   /**
   * Get commentsCount
   * @return commentsCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getCommentsCount() {
    return commentsCount;
  }

  public void setCommentsCount(Integer commentsCount) {
    this.commentsCount = commentsCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InsiderPostModel insiderPostModel = (InsiderPostModel) o;
    return Objects.equals(this.postTitle, insiderPostModel.postTitle) &&
        Objects.equals(this.postDateTime, insiderPostModel.postDateTime) &&
        Objects.equals(this.insiderUrl, insiderPostModel.insiderUrl) &&
        Objects.equals(this.authorName, insiderPostModel.authorName) &&
        Objects.equals(this.postContent, insiderPostModel.postContent) &&
        Objects.equals(this.commentsCount, insiderPostModel.commentsCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postTitle, postDateTime, insiderUrl, authorName, postContent, commentsCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InsiderPostModel {\n");
    
    sb.append("    postTitle: ").append(toIndentedString(postTitle)).append("\n");
    sb.append("    postDateTime: ").append(toIndentedString(postDateTime)).append("\n");
    sb.append("    insiderUrl: ").append(toIndentedString(insiderUrl)).append("\n");
    sb.append("    authorName: ").append(toIndentedString(authorName)).append("\n");
    sb.append("    postContent: ").append(toIndentedString(postContent)).append("\n");
    sb.append("    commentsCount: ").append(toIndentedString(commentsCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

