/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * MatchPlayStatisticsModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class MatchPlayStatisticsModel {
  @SerializedName("MatchPlayStatisticsId")
  private Long matchPlayStatisticsId = null;

  @SerializedName("EntityId")
  private Long entityId = null;

  @SerializedName("MatchesPlayedCount")
  private Integer matchesPlayedCount = null;

  @SerializedName("WonCount")
  private Integer wonCount = null;

  @SerializedName("LostCount")
  private Integer lostCount = null;

  @SerializedName("TieCount")
  private Integer tieCount = null;

  @SerializedName("ForfeitedWonCount")
  private Integer forfeitedWonCount = null;

  @SerializedName("ForfeitedLostCount")
  private Integer forfeitedLostCount = null;

  @SerializedName("NoShowCount")
  private Integer noShowCount = null;

  @SerializedName("TotalWinnings")
  private Double totalWinnings = null;

  @SerializedName("TotalScore")
  private Float totalScore = null;

  @SerializedName("TotalTimePlayedInSeconds")
  private Long totalTimePlayedInSeconds = null;

  @SerializedName("WinStreak")
  private Integer winStreak = null;

  @SerializedName("LossStreak")
  private Integer lossStreak = null;

  public MatchPlayStatisticsModel matchPlayStatisticsId(Long matchPlayStatisticsId) {
    this.matchPlayStatisticsId = matchPlayStatisticsId;
    return this;
  }

   /**
   * Get matchPlayStatisticsId
   * @return matchPlayStatisticsId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getMatchPlayStatisticsId() {
    return matchPlayStatisticsId;
  }

  public void setMatchPlayStatisticsId(Long matchPlayStatisticsId) {
    this.matchPlayStatisticsId = matchPlayStatisticsId;
  }

  public MatchPlayStatisticsModel entityId(Long entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * Get entityId
   * @return entityId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getEntityId() {
    return entityId;
  }

  public void setEntityId(Long entityId) {
    this.entityId = entityId;
  }

  public MatchPlayStatisticsModel matchesPlayedCount(Integer matchesPlayedCount) {
    this.matchesPlayedCount = matchesPlayedCount;
    return this;
  }

   /**
   * Get matchesPlayedCount
   * @return matchesPlayedCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getMatchesPlayedCount() {
    return matchesPlayedCount;
  }

  public void setMatchesPlayedCount(Integer matchesPlayedCount) {
    this.matchesPlayedCount = matchesPlayedCount;
  }

  public MatchPlayStatisticsModel wonCount(Integer wonCount) {
    this.wonCount = wonCount;
    return this;
  }

   /**
   * Get wonCount
   * @return wonCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWonCount() {
    return wonCount;
  }

  public void setWonCount(Integer wonCount) {
    this.wonCount = wonCount;
  }

  public MatchPlayStatisticsModel lostCount(Integer lostCount) {
    this.lostCount = lostCount;
    return this;
  }

   /**
   * Get lostCount
   * @return lostCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLostCount() {
    return lostCount;
  }

  public void setLostCount(Integer lostCount) {
    this.lostCount = lostCount;
  }

  public MatchPlayStatisticsModel tieCount(Integer tieCount) {
    this.tieCount = tieCount;
    return this;
  }

   /**
   * Get tieCount
   * @return tieCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTieCount() {
    return tieCount;
  }

  public void setTieCount(Integer tieCount) {
    this.tieCount = tieCount;
  }

  public MatchPlayStatisticsModel forfeitedWonCount(Integer forfeitedWonCount) {
    this.forfeitedWonCount = forfeitedWonCount;
    return this;
  }

   /**
   * Get forfeitedWonCount
   * @return forfeitedWonCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getForfeitedWonCount() {
    return forfeitedWonCount;
  }

  public void setForfeitedWonCount(Integer forfeitedWonCount) {
    this.forfeitedWonCount = forfeitedWonCount;
  }

  public MatchPlayStatisticsModel forfeitedLostCount(Integer forfeitedLostCount) {
    this.forfeitedLostCount = forfeitedLostCount;
    return this;
  }

   /**
   * Get forfeitedLostCount
   * @return forfeitedLostCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getForfeitedLostCount() {
    return forfeitedLostCount;
  }

  public void setForfeitedLostCount(Integer forfeitedLostCount) {
    this.forfeitedLostCount = forfeitedLostCount;
  }

  public MatchPlayStatisticsModel noShowCount(Integer noShowCount) {
    this.noShowCount = noShowCount;
    return this;
  }

   /**
   * Get noShowCount
   * @return noShowCount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNoShowCount() {
    return noShowCount;
  }

  public void setNoShowCount(Integer noShowCount) {
    this.noShowCount = noShowCount;
  }

  public MatchPlayStatisticsModel totalWinnings(Double totalWinnings) {
    this.totalWinnings = totalWinnings;
    return this;
  }

   /**
   * Get totalWinnings
   * @return totalWinnings
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getTotalWinnings() {
    return totalWinnings;
  }

  public void setTotalWinnings(Double totalWinnings) {
    this.totalWinnings = totalWinnings;
  }

  public MatchPlayStatisticsModel totalScore(Float totalScore) {
    this.totalScore = totalScore;
    return this;
  }

   /**
   * Get totalScore
   * @return totalScore
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getTotalScore() {
    return totalScore;
  }

  public void setTotalScore(Float totalScore) {
    this.totalScore = totalScore;
  }

  public MatchPlayStatisticsModel totalTimePlayedInSeconds(Long totalTimePlayedInSeconds) {
    this.totalTimePlayedInSeconds = totalTimePlayedInSeconds;
    return this;
  }

   /**
   * Get totalTimePlayedInSeconds
   * @return totalTimePlayedInSeconds
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTotalTimePlayedInSeconds() {
    return totalTimePlayedInSeconds;
  }

  public void setTotalTimePlayedInSeconds(Long totalTimePlayedInSeconds) {
    this.totalTimePlayedInSeconds = totalTimePlayedInSeconds;
  }

  public MatchPlayStatisticsModel winStreak(Integer winStreak) {
    this.winStreak = winStreak;
    return this;
  }

   /**
   * Get winStreak
   * @return winStreak
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getWinStreak() {
    return winStreak;
  }

  public void setWinStreak(Integer winStreak) {
    this.winStreak = winStreak;
  }

  public MatchPlayStatisticsModel lossStreak(Integer lossStreak) {
    this.lossStreak = lossStreak;
    return this;
  }

   /**
   * Get lossStreak
   * @return lossStreak
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getLossStreak() {
    return lossStreak;
  }

  public void setLossStreak(Integer lossStreak) {
    this.lossStreak = lossStreak;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MatchPlayStatisticsModel matchPlayStatisticsModel = (MatchPlayStatisticsModel) o;
    return Objects.equals(this.matchPlayStatisticsId, matchPlayStatisticsModel.matchPlayStatisticsId) &&
        Objects.equals(this.entityId, matchPlayStatisticsModel.entityId) &&
        Objects.equals(this.matchesPlayedCount, matchPlayStatisticsModel.matchesPlayedCount) &&
        Objects.equals(this.wonCount, matchPlayStatisticsModel.wonCount) &&
        Objects.equals(this.lostCount, matchPlayStatisticsModel.lostCount) &&
        Objects.equals(this.tieCount, matchPlayStatisticsModel.tieCount) &&
        Objects.equals(this.forfeitedWonCount, matchPlayStatisticsModel.forfeitedWonCount) &&
        Objects.equals(this.forfeitedLostCount, matchPlayStatisticsModel.forfeitedLostCount) &&
        Objects.equals(this.noShowCount, matchPlayStatisticsModel.noShowCount) &&
        Objects.equals(this.totalWinnings, matchPlayStatisticsModel.totalWinnings) &&
        Objects.equals(this.totalScore, matchPlayStatisticsModel.totalScore) &&
        Objects.equals(this.totalTimePlayedInSeconds, matchPlayStatisticsModel.totalTimePlayedInSeconds) &&
        Objects.equals(this.winStreak, matchPlayStatisticsModel.winStreak) &&
        Objects.equals(this.lossStreak, matchPlayStatisticsModel.lossStreak);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchPlayStatisticsId, entityId, matchesPlayedCount, wonCount, lostCount, tieCount, forfeitedWonCount, forfeitedLostCount, noShowCount, totalWinnings, totalScore, totalTimePlayedInSeconds, winStreak, lossStreak);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MatchPlayStatisticsModel {\n");
    
    sb.append("    matchPlayStatisticsId: ").append(toIndentedString(matchPlayStatisticsId)).append("\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    matchesPlayedCount: ").append(toIndentedString(matchesPlayedCount)).append("\n");
    sb.append("    wonCount: ").append(toIndentedString(wonCount)).append("\n");
    sb.append("    lostCount: ").append(toIndentedString(lostCount)).append("\n");
    sb.append("    tieCount: ").append(toIndentedString(tieCount)).append("\n");
    sb.append("    forfeitedWonCount: ").append(toIndentedString(forfeitedWonCount)).append("\n");
    sb.append("    forfeitedLostCount: ").append(toIndentedString(forfeitedLostCount)).append("\n");
    sb.append("    noShowCount: ").append(toIndentedString(noShowCount)).append("\n");
    sb.append("    totalWinnings: ").append(toIndentedString(totalWinnings)).append("\n");
    sb.append("    totalScore: ").append(toIndentedString(totalScore)).append("\n");
    sb.append("    totalTimePlayedInSeconds: ").append(toIndentedString(totalTimePlayedInSeconds)).append("\n");
    sb.append("    winStreak: ").append(toIndentedString(winStreak)).append("\n");
    sb.append("    lossStreak: ").append(toIndentedString(lossStreak)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

