/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.NotificationListModel;

/**
 * NotificationProfileCompleteOutputModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class NotificationProfileCompleteOutputModel {
  @SerializedName("DismissedNotifications")
  private NotificationListModel dismissedNotifications = null;

  @SerializedName("PendingNotifications")
  private NotificationListModel pendingNotifications = null;

  public NotificationProfileCompleteOutputModel dismissedNotifications(NotificationListModel dismissedNotifications) {
    this.dismissedNotifications = dismissedNotifications;
    return this;
  }

   /**
   * Get dismissedNotifications
   * @return dismissedNotifications
  **/
  @ApiModelProperty(example = "null", value = "")
  public NotificationListModel getDismissedNotifications() {
    return dismissedNotifications;
  }

  public void setDismissedNotifications(NotificationListModel dismissedNotifications) {
    this.dismissedNotifications = dismissedNotifications;
  }

  public NotificationProfileCompleteOutputModel pendingNotifications(NotificationListModel pendingNotifications) {
    this.pendingNotifications = pendingNotifications;
    return this;
  }

   /**
   * Get pendingNotifications
   * @return pendingNotifications
  **/
  @ApiModelProperty(example = "null", value = "")
  public NotificationListModel getPendingNotifications() {
    return pendingNotifications;
  }

  public void setPendingNotifications(NotificationListModel pendingNotifications) {
    this.pendingNotifications = pendingNotifications;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationProfileCompleteOutputModel notificationProfileCompleteOutputModel = (NotificationProfileCompleteOutputModel) o;
    return Objects.equals(this.dismissedNotifications, notificationProfileCompleteOutputModel.dismissedNotifications) &&
        Objects.equals(this.pendingNotifications, notificationProfileCompleteOutputModel.pendingNotifications);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dismissedNotifications, pendingNotifications);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationProfileCompleteOutputModel {\n");
    
    sb.append("    dismissedNotifications: ").append(toIndentedString(dismissedNotifications)).append("\n");
    sb.append("    pendingNotifications: ").append(toIndentedString(pendingNotifications)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

