/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * SocialActionMessageAttributeModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class SocialActionMessageAttributeModel {
  @SerializedName("AttributeId")
  private Integer attributeId = null;

  @SerializedName("DisplayName")
  private String displayName = null;

  @SerializedName("LinkType")
  private String linkType = null;

  @SerializedName("LinkAttribute")
  private String linkAttribute = null;

  public SocialActionMessageAttributeModel attributeId(Integer attributeId) {
    this.attributeId = attributeId;
    return this;
  }

   /**
   * Get attributeId
   * @return attributeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getAttributeId() {
    return attributeId;
  }

  public void setAttributeId(Integer attributeId) {
    this.attributeId = attributeId;
  }

  public SocialActionMessageAttributeModel displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public SocialActionMessageAttributeModel linkType(String linkType) {
    this.linkType = linkType;
    return this;
  }

   /**
   * Get linkType
   * @return linkType
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLinkType() {
    return linkType;
  }

  public void setLinkType(String linkType) {
    this.linkType = linkType;
  }

  public SocialActionMessageAttributeModel linkAttribute(String linkAttribute) {
    this.linkAttribute = linkAttribute;
    return this;
  }

   /**
   * Get linkAttribute
   * @return linkAttribute
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLinkAttribute() {
    return linkAttribute;
  }

  public void setLinkAttribute(String linkAttribute) {
    this.linkAttribute = linkAttribute;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SocialActionMessageAttributeModel socialActionMessageAttributeModel = (SocialActionMessageAttributeModel) o;
    return Objects.equals(this.attributeId, socialActionMessageAttributeModel.attributeId) &&
        Objects.equals(this.displayName, socialActionMessageAttributeModel.displayName) &&
        Objects.equals(this.linkType, socialActionMessageAttributeModel.linkType) &&
        Objects.equals(this.linkAttribute, socialActionMessageAttributeModel.linkAttribute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attributeId, displayName, linkType, linkAttribute);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SocialActionMessageAttributeModel {\n");
    
    sb.append("    attributeId: ").append(toIndentedString(attributeId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    linkType: ").append(toIndentedString(linkType)).append("\n");
    sb.append("    linkAttribute: ").append(toIndentedString(linkAttribute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

