/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * TournamentAnnouncementModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class TournamentAnnouncementModel {
  @SerializedName("TournamentAnnouncementId")
  private Long tournamentAnnouncementId = null;

  @SerializedName("TournamentId")
  private Long tournamentId = null;

  @SerializedName("TournamentAnnouncement")
  private String tournamentAnnouncement = null;

  @SerializedName("CreatedDateTime")
  private DateTime createdDateTime = null;

  @SerializedName("CreatedById")
  private Long createdById = null;

  @SerializedName("EntityName")
  private String entityName = null;

  @SerializedName("DisplayName")
  private String displayName = null;

  public TournamentAnnouncementModel tournamentAnnouncementId(Long tournamentAnnouncementId) {
    this.tournamentAnnouncementId = tournamentAnnouncementId;
    return this;
  }

   /**
   * Get tournamentAnnouncementId
   * @return tournamentAnnouncementId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTournamentAnnouncementId() {
    return tournamentAnnouncementId;
  }

  public void setTournamentAnnouncementId(Long tournamentAnnouncementId) {
    this.tournamentAnnouncementId = tournamentAnnouncementId;
  }

  public TournamentAnnouncementModel tournamentId(Long tournamentId) {
    this.tournamentId = tournamentId;
    return this;
  }

   /**
   * Get tournamentId
   * @return tournamentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTournamentId() {
    return tournamentId;
  }

  public void setTournamentId(Long tournamentId) {
    this.tournamentId = tournamentId;
  }

  public TournamentAnnouncementModel tournamentAnnouncement(String tournamentAnnouncement) {
    this.tournamentAnnouncement = tournamentAnnouncement;
    return this;
  }

   /**
   * Get tournamentAnnouncement
   * @return tournamentAnnouncement
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTournamentAnnouncement() {
    return tournamentAnnouncement;
  }

  public void setTournamentAnnouncement(String tournamentAnnouncement) {
    this.tournamentAnnouncement = tournamentAnnouncement;
  }

  public TournamentAnnouncementModel createdDateTime(DateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
    return this;
  }

   /**
   * Get createdDateTime
   * @return createdDateTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getCreatedDateTime() {
    return createdDateTime;
  }

  public void setCreatedDateTime(DateTime createdDateTime) {
    this.createdDateTime = createdDateTime;
  }

  public TournamentAnnouncementModel createdById(Long createdById) {
    this.createdById = createdById;
    return this;
  }

   /**
   * Get createdById
   * @return createdById
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getCreatedById() {
    return createdById;
  }

  public void setCreatedById(Long createdById) {
    this.createdById = createdById;
  }

  public TournamentAnnouncementModel entityName(String entityName) {
    this.entityName = entityName;
    return this;
  }

   /**
   * Get entityName
   * @return entityName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getEntityName() {
    return entityName;
  }

  public void setEntityName(String entityName) {
    this.entityName = entityName;
  }

  public TournamentAnnouncementModel displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Get displayName
   * @return displayName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TournamentAnnouncementModel tournamentAnnouncementModel = (TournamentAnnouncementModel) o;
    return Objects.equals(this.tournamentAnnouncementId, tournamentAnnouncementModel.tournamentAnnouncementId) &&
        Objects.equals(this.tournamentId, tournamentAnnouncementModel.tournamentId) &&
        Objects.equals(this.tournamentAnnouncement, tournamentAnnouncementModel.tournamentAnnouncement) &&
        Objects.equals(this.createdDateTime, tournamentAnnouncementModel.createdDateTime) &&
        Objects.equals(this.createdById, tournamentAnnouncementModel.createdById) &&
        Objects.equals(this.entityName, tournamentAnnouncementModel.entityName) &&
        Objects.equals(this.displayName, tournamentAnnouncementModel.displayName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tournamentAnnouncementId, tournamentId, tournamentAnnouncement, createdDateTime, createdById, entityName, displayName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TournamentAnnouncementModel {\n");
    
    sb.append("    tournamentAnnouncementId: ").append(toIndentedString(tournamentAnnouncementId)).append("\n");
    sb.append("    tournamentId: ").append(toIndentedString(tournamentId)).append("\n");
    sb.append("    tournamentAnnouncement: ").append(toIndentedString(tournamentAnnouncement)).append("\n");
    sb.append("    createdDateTime: ").append(toIndentedString(createdDateTime)).append("\n");
    sb.append("    createdById: ").append(toIndentedString(createdById)).append("\n");
    sb.append("    entityName: ").append(toIndentedString(entityName)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

