/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.EntityProfileModel;
import org.joda.time.DateTime;

/**
 * TournamentPayoutModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class TournamentPayoutModel {
  @SerializedName("TournamentId")
  private Long tournamentId = null;

  @SerializedName("PlaceNumber")
  private Integer placeNumber = null;

  @SerializedName("PayoutAmount")
  private Double payoutAmount = null;

  @SerializedName("OtherPayout")
  private String otherPayout = null;

  @SerializedName("AwardedToEntityId")
  private Long awardedToEntityId = null;

  @SerializedName("AwardedToEntityProfile")
  private EntityProfileModel awardedToEntityProfile = null;

  @SerializedName("AwardedDateTime")
  private DateTime awardedDateTime = null;

  @SerializedName("IsAwarded")
  private Boolean isAwarded = null;

  @SerializedName("BrandName")
  private String brandName = null;

  @SerializedName("ProductName")
  private String productName = null;

  @SerializedName("Description")
  private String description = null;

  @SerializedName("LearnMoreUrl")
  private String learnMoreUrl = null;

  @SerializedName("ProductImageUrl")
  private String productImageUrl = null;

  public TournamentPayoutModel tournamentId(Long tournamentId) {
    this.tournamentId = tournamentId;
    return this;
  }

   /**
   * Get tournamentId
   * @return tournamentId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTournamentId() {
    return tournamentId;
  }

  public void setTournamentId(Long tournamentId) {
    this.tournamentId = tournamentId;
  }

  public TournamentPayoutModel placeNumber(Integer placeNumber) {
    this.placeNumber = placeNumber;
    return this;
  }

   /**
   * Get placeNumber
   * @return placeNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getPlaceNumber() {
    return placeNumber;
  }

  public void setPlaceNumber(Integer placeNumber) {
    this.placeNumber = placeNumber;
  }

  public TournamentPayoutModel payoutAmount(Double payoutAmount) {
    this.payoutAmount = payoutAmount;
    return this;
  }

   /**
   * Get payoutAmount
   * @return payoutAmount
  **/
  @ApiModelProperty(example = "null", value = "")
  public Double getPayoutAmount() {
    return payoutAmount;
  }

  public void setPayoutAmount(Double payoutAmount) {
    this.payoutAmount = payoutAmount;
  }

  public TournamentPayoutModel otherPayout(String otherPayout) {
    this.otherPayout = otherPayout;
    return this;
  }

   /**
   * Get otherPayout
   * @return otherPayout
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getOtherPayout() {
    return otherPayout;
  }

  public void setOtherPayout(String otherPayout) {
    this.otherPayout = otherPayout;
  }

  public TournamentPayoutModel awardedToEntityId(Long awardedToEntityId) {
    this.awardedToEntityId = awardedToEntityId;
    return this;
  }

   /**
   * Get awardedToEntityId
   * @return awardedToEntityId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAwardedToEntityId() {
    return awardedToEntityId;
  }

  public void setAwardedToEntityId(Long awardedToEntityId) {
    this.awardedToEntityId = awardedToEntityId;
  }

  public TournamentPayoutModel awardedToEntityProfile(EntityProfileModel awardedToEntityProfile) {
    this.awardedToEntityProfile = awardedToEntityProfile;
    return this;
  }

   /**
   * Get awardedToEntityProfile
   * @return awardedToEntityProfile
  **/
  @ApiModelProperty(example = "null", value = "")
  public EntityProfileModel getAwardedToEntityProfile() {
    return awardedToEntityProfile;
  }

  public void setAwardedToEntityProfile(EntityProfileModel awardedToEntityProfile) {
    this.awardedToEntityProfile = awardedToEntityProfile;
  }

  public TournamentPayoutModel awardedDateTime(DateTime awardedDateTime) {
    this.awardedDateTime = awardedDateTime;
    return this;
  }

   /**
   * Get awardedDateTime
   * @return awardedDateTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getAwardedDateTime() {
    return awardedDateTime;
  }

  public void setAwardedDateTime(DateTime awardedDateTime) {
    this.awardedDateTime = awardedDateTime;
  }

   /**
   * Get isAwarded
   * @return isAwarded
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsAwarded() {
    return isAwarded;
  }

  public TournamentPayoutModel brandName(String brandName) {
    this.brandName = brandName;
    return this;
  }

   /**
   * Get brandName
   * @return brandName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getBrandName() {
    return brandName;
  }

  public void setBrandName(String brandName) {
    this.brandName = brandName;
  }

  public TournamentPayoutModel productName(String productName) {
    this.productName = productName;
    return this;
  }

   /**
   * Get productName
   * @return productName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProductName() {
    return productName;
  }

  public void setProductName(String productName) {
    this.productName = productName;
  }

  public TournamentPayoutModel description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TournamentPayoutModel learnMoreUrl(String learnMoreUrl) {
    this.learnMoreUrl = learnMoreUrl;
    return this;
  }

   /**
   * Get learnMoreUrl
   * @return learnMoreUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getLearnMoreUrl() {
    return learnMoreUrl;
  }

  public void setLearnMoreUrl(String learnMoreUrl) {
    this.learnMoreUrl = learnMoreUrl;
  }

  public TournamentPayoutModel productImageUrl(String productImageUrl) {
    this.productImageUrl = productImageUrl;
    return this;
  }

   /**
   * Get productImageUrl
   * @return productImageUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getProductImageUrl() {
    return productImageUrl;
  }

  public void setProductImageUrl(String productImageUrl) {
    this.productImageUrl = productImageUrl;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TournamentPayoutModel tournamentPayoutModel = (TournamentPayoutModel) o;
    return Objects.equals(this.tournamentId, tournamentPayoutModel.tournamentId) &&
        Objects.equals(this.placeNumber, tournamentPayoutModel.placeNumber) &&
        Objects.equals(this.payoutAmount, tournamentPayoutModel.payoutAmount) &&
        Objects.equals(this.otherPayout, tournamentPayoutModel.otherPayout) &&
        Objects.equals(this.awardedToEntityId, tournamentPayoutModel.awardedToEntityId) &&
        Objects.equals(this.awardedToEntityProfile, tournamentPayoutModel.awardedToEntityProfile) &&
        Objects.equals(this.awardedDateTime, tournamentPayoutModel.awardedDateTime) &&
        Objects.equals(this.isAwarded, tournamentPayoutModel.isAwarded) &&
        Objects.equals(this.brandName, tournamentPayoutModel.brandName) &&
        Objects.equals(this.productName, tournamentPayoutModel.productName) &&
        Objects.equals(this.description, tournamentPayoutModel.description) &&
        Objects.equals(this.learnMoreUrl, tournamentPayoutModel.learnMoreUrl) &&
        Objects.equals(this.productImageUrl, tournamentPayoutModel.productImageUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tournamentId, placeNumber, payoutAmount, otherPayout, awardedToEntityId, awardedToEntityProfile, awardedDateTime, isAwarded, brandName, productName, description, learnMoreUrl, productImageUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TournamentPayoutModel {\n");
    
    sb.append("    tournamentId: ").append(toIndentedString(tournamentId)).append("\n");
    sb.append("    placeNumber: ").append(toIndentedString(placeNumber)).append("\n");
    sb.append("    payoutAmount: ").append(toIndentedString(payoutAmount)).append("\n");
    sb.append("    otherPayout: ").append(toIndentedString(otherPayout)).append("\n");
    sb.append("    awardedToEntityId: ").append(toIndentedString(awardedToEntityId)).append("\n");
    sb.append("    awardedToEntityProfile: ").append(toIndentedString(awardedToEntityProfile)).append("\n");
    sb.append("    awardedDateTime: ").append(toIndentedString(awardedDateTime)).append("\n");
    sb.append("    isAwarded: ").append(toIndentedString(isAwarded)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    productName: ").append(toIndentedString(productName)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    learnMoreUrl: ").append(toIndentedString(learnMoreUrl)).append("\n");
    sb.append("    productImageUrl: ").append(toIndentedString(productImageUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

