/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TournamentJoinTypeModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class TournamentJoinTypeModel {
  @SerializedName("TournamentJoinTypeId")
  private Integer tournamentJoinTypeId = null;

  @SerializedName("TournamentJoinTypeName")
  private String tournamentJoinTypeName = null;

  public TournamentJoinTypeModel tournamentJoinTypeId(Integer tournamentJoinTypeId) {
    this.tournamentJoinTypeId = tournamentJoinTypeId;
    return this;
  }

   /**
   * Get tournamentJoinTypeId
   * @return tournamentJoinTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTournamentJoinTypeId() {
    return tournamentJoinTypeId;
  }

  public void setTournamentJoinTypeId(Integer tournamentJoinTypeId) {
    this.tournamentJoinTypeId = tournamentJoinTypeId;
  }

  public TournamentJoinTypeModel tournamentJoinTypeName(String tournamentJoinTypeName) {
    this.tournamentJoinTypeName = tournamentJoinTypeName;
    return this;
  }

   /**
   * Get tournamentJoinTypeName
   * @return tournamentJoinTypeName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getTournamentJoinTypeName() {
    return tournamentJoinTypeName;
  }

  public void setTournamentJoinTypeName(String tournamentJoinTypeName) {
    this.tournamentJoinTypeName = tournamentJoinTypeName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TournamentJoinTypeModel tournamentJoinTypeModel = (TournamentJoinTypeModel) o;
    return Objects.equals(this.tournamentJoinTypeId, tournamentJoinTypeModel.tournamentJoinTypeId) &&
        Objects.equals(this.tournamentJoinTypeName, tournamentJoinTypeModel.tournamentJoinTypeName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tournamentJoinTypeId, tournamentJoinTypeName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TournamentJoinTypeModel {\n");
    
    sb.append("    tournamentJoinTypeId: ").append(toIndentedString(tournamentJoinTypeId)).append("\n");
    sb.append("    tournamentJoinTypeName: ").append(toIndentedString(tournamentJoinTypeName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

