/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TournamentParticipantQualifierTieBreakerModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class TournamentParticipantQualifierTieBreakerModel {
  @SerializedName("RoundNumber")
  private Integer roundNumber = null;

  @SerializedName("TieBreakerLevelId")
  private Integer tieBreakerLevelId = null;

  @SerializedName("TieBreakerTypeId")
  private Integer tieBreakerTypeId = null;

  @SerializedName("TieBreakerValue")
  private Float tieBreakerValue = null;

  public TournamentParticipantQualifierTieBreakerModel roundNumber(Integer roundNumber) {
    this.roundNumber = roundNumber;
    return this;
  }

   /**
   * Get roundNumber
   * @return roundNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getRoundNumber() {
    return roundNumber;
  }

  public void setRoundNumber(Integer roundNumber) {
    this.roundNumber = roundNumber;
  }

  public TournamentParticipantQualifierTieBreakerModel tieBreakerLevelId(Integer tieBreakerLevelId) {
    this.tieBreakerLevelId = tieBreakerLevelId;
    return this;
  }

   /**
   * Get tieBreakerLevelId
   * @return tieBreakerLevelId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTieBreakerLevelId() {
    return tieBreakerLevelId;
  }

  public void setTieBreakerLevelId(Integer tieBreakerLevelId) {
    this.tieBreakerLevelId = tieBreakerLevelId;
  }

  public TournamentParticipantQualifierTieBreakerModel tieBreakerTypeId(Integer tieBreakerTypeId) {
    this.tieBreakerTypeId = tieBreakerTypeId;
    return this;
  }

   /**
   * Get tieBreakerTypeId
   * @return tieBreakerTypeId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getTieBreakerTypeId() {
    return tieBreakerTypeId;
  }

  public void setTieBreakerTypeId(Integer tieBreakerTypeId) {
    this.tieBreakerTypeId = tieBreakerTypeId;
  }

  public TournamentParticipantQualifierTieBreakerModel tieBreakerValue(Float tieBreakerValue) {
    this.tieBreakerValue = tieBreakerValue;
    return this;
  }

   /**
   * Get tieBreakerValue
   * @return tieBreakerValue
  **/
  @ApiModelProperty(example = "null", value = "")
  public Float getTieBreakerValue() {
    return tieBreakerValue;
  }

  public void setTieBreakerValue(Float tieBreakerValue) {
    this.tieBreakerValue = tieBreakerValue;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TournamentParticipantQualifierTieBreakerModel tournamentParticipantQualifierTieBreakerModel = (TournamentParticipantQualifierTieBreakerModel) o;
    return Objects.equals(this.roundNumber, tournamentParticipantQualifierTieBreakerModel.roundNumber) &&
        Objects.equals(this.tieBreakerLevelId, tournamentParticipantQualifierTieBreakerModel.tieBreakerLevelId) &&
        Objects.equals(this.tieBreakerTypeId, tournamentParticipantQualifierTieBreakerModel.tieBreakerTypeId) &&
        Objects.equals(this.tieBreakerValue, tournamentParticipantQualifierTieBreakerModel.tieBreakerValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(roundNumber, tieBreakerLevelId, tieBreakerTypeId, tieBreakerValue);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TournamentParticipantQualifierTieBreakerModel {\n");
    
    sb.append("    roundNumber: ").append(toIndentedString(roundNumber)).append("\n");
    sb.append("    tieBreakerLevelId: ").append(toIndentedString(tieBreakerLevelId)).append("\n");
    sb.append("    tieBreakerTypeId: ").append(toIndentedString(tieBreakerTypeId)).append("\n");
    sb.append("    tieBreakerValue: ").append(toIndentedString(tieBreakerValue)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

