/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * TournamentMatchMyActiveMatchModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class TournamentMatchMyActiveMatchModel {
  @SerializedName("TournamentMatchId")
  private Long tournamentMatchId = null;

  @SerializedName("GameName")
  private String gameName = null;

  @SerializedName("GameImageLargeUrl")
  private String gameImageLargeUrl = null;

  @SerializedName("TournamentMatchIsTeam")
  private Boolean tournamentMatchIsTeam = null;

  @SerializedName("ParticipantAEntityName")
  private String participantAEntityName = null;

  @SerializedName("ParticipantANickname")
  private String participantANickname = null;

  @SerializedName("ParticipantBEntityName")
  private String participantBEntityName = null;

  @SerializedName("ParticipantBNickname")
  private String participantBNickname = null;

  @SerializedName("ScheduledStartDateTime")
  private DateTime scheduledStartDateTime = null;

  public TournamentMatchMyActiveMatchModel tournamentMatchId(Long tournamentMatchId) {
    this.tournamentMatchId = tournamentMatchId;
    return this;
  }

   /**
   * Get tournamentMatchId
   * @return tournamentMatchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTournamentMatchId() {
    return tournamentMatchId;
  }

  public void setTournamentMatchId(Long tournamentMatchId) {
    this.tournamentMatchId = tournamentMatchId;
  }

  public TournamentMatchMyActiveMatchModel gameName(String gameName) {
    this.gameName = gameName;
    return this;
  }

   /**
   * Get gameName
   * @return gameName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameName() {
    return gameName;
  }

  public void setGameName(String gameName) {
    this.gameName = gameName;
  }

  public TournamentMatchMyActiveMatchModel gameImageLargeUrl(String gameImageLargeUrl) {
    this.gameImageLargeUrl = gameImageLargeUrl;
    return this;
  }

   /**
   * Get gameImageLargeUrl
   * @return gameImageLargeUrl
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGameImageLargeUrl() {
    return gameImageLargeUrl;
  }

  public void setGameImageLargeUrl(String gameImageLargeUrl) {
    this.gameImageLargeUrl = gameImageLargeUrl;
  }

  public TournamentMatchMyActiveMatchModel tournamentMatchIsTeam(Boolean tournamentMatchIsTeam) {
    this.tournamentMatchIsTeam = tournamentMatchIsTeam;
    return this;
  }

   /**
   * Get tournamentMatchIsTeam
   * @return tournamentMatchIsTeam
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getTournamentMatchIsTeam() {
    return tournamentMatchIsTeam;
  }

  public void setTournamentMatchIsTeam(Boolean tournamentMatchIsTeam) {
    this.tournamentMatchIsTeam = tournamentMatchIsTeam;
  }

  public TournamentMatchMyActiveMatchModel participantAEntityName(String participantAEntityName) {
    this.participantAEntityName = participantAEntityName;
    return this;
  }

   /**
   * Get participantAEntityName
   * @return participantAEntityName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getParticipantAEntityName() {
    return participantAEntityName;
  }

  public void setParticipantAEntityName(String participantAEntityName) {
    this.participantAEntityName = participantAEntityName;
  }

  public TournamentMatchMyActiveMatchModel participantANickname(String participantANickname) {
    this.participantANickname = participantANickname;
    return this;
  }

   /**
   * Get participantANickname
   * @return participantANickname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getParticipantANickname() {
    return participantANickname;
  }

  public void setParticipantANickname(String participantANickname) {
    this.participantANickname = participantANickname;
  }

  public TournamentMatchMyActiveMatchModel participantBEntityName(String participantBEntityName) {
    this.participantBEntityName = participantBEntityName;
    return this;
  }

   /**
   * Get participantBEntityName
   * @return participantBEntityName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getParticipantBEntityName() {
    return participantBEntityName;
  }

  public void setParticipantBEntityName(String participantBEntityName) {
    this.participantBEntityName = participantBEntityName;
  }

  public TournamentMatchMyActiveMatchModel participantBNickname(String participantBNickname) {
    this.participantBNickname = participantBNickname;
    return this;
  }

   /**
   * Get participantBNickname
   * @return participantBNickname
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getParticipantBNickname() {
    return participantBNickname;
  }

  public void setParticipantBNickname(String participantBNickname) {
    this.participantBNickname = participantBNickname;
  }

  public TournamentMatchMyActiveMatchModel scheduledStartDateTime(DateTime scheduledStartDateTime) {
    this.scheduledStartDateTime = scheduledStartDateTime;
    return this;
  }

   /**
   * Get scheduledStartDateTime
   * @return scheduledStartDateTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getScheduledStartDateTime() {
    return scheduledStartDateTime;
  }

  public void setScheduledStartDateTime(DateTime scheduledStartDateTime) {
    this.scheduledStartDateTime = scheduledStartDateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TournamentMatchMyActiveMatchModel tournamentMatchMyActiveMatchModel = (TournamentMatchMyActiveMatchModel) o;
    return Objects.equals(this.tournamentMatchId, tournamentMatchMyActiveMatchModel.tournamentMatchId) &&
        Objects.equals(this.gameName, tournamentMatchMyActiveMatchModel.gameName) &&
        Objects.equals(this.gameImageLargeUrl, tournamentMatchMyActiveMatchModel.gameImageLargeUrl) &&
        Objects.equals(this.tournamentMatchIsTeam, tournamentMatchMyActiveMatchModel.tournamentMatchIsTeam) &&
        Objects.equals(this.participantAEntityName, tournamentMatchMyActiveMatchModel.participantAEntityName) &&
        Objects.equals(this.participantANickname, tournamentMatchMyActiveMatchModel.participantANickname) &&
        Objects.equals(this.participantBEntityName, tournamentMatchMyActiveMatchModel.participantBEntityName) &&
        Objects.equals(this.participantBNickname, tournamentMatchMyActiveMatchModel.participantBNickname) &&
        Objects.equals(this.scheduledStartDateTime, tournamentMatchMyActiveMatchModel.scheduledStartDateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tournamentMatchId, gameName, gameImageLargeUrl, tournamentMatchIsTeam, participantAEntityName, participantANickname, participantBEntityName, participantBNickname, scheduledStartDateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TournamentMatchMyActiveMatchModel {\n");
    
    sb.append("    tournamentMatchId: ").append(toIndentedString(tournamentMatchId)).append("\n");
    sb.append("    gameName: ").append(toIndentedString(gameName)).append("\n");
    sb.append("    gameImageLargeUrl: ").append(toIndentedString(gameImageLargeUrl)).append("\n");
    sb.append("    tournamentMatchIsTeam: ").append(toIndentedString(tournamentMatchIsTeam)).append("\n");
    sb.append("    participantAEntityName: ").append(toIndentedString(participantAEntityName)).append("\n");
    sb.append("    participantANickname: ").append(toIndentedString(participantANickname)).append("\n");
    sb.append("    participantBEntityName: ").append(toIndentedString(participantBEntityName)).append("\n");
    sb.append("    participantBNickname: ").append(toIndentedString(participantBNickname)).append("\n");
    sb.append("    scheduledStartDateTime: ").append(toIndentedString(scheduledStartDateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

