/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

/**
 * TournamentQualifierGroupModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class TournamentQualifierGroupModel {
  @SerializedName("GroupNumber")
  private Integer groupNumber = null;

  @SerializedName("GroupName")
  private String groupName = null;

  @SerializedName("IsGuaranteedPlayoffs")
  private Boolean isGuaranteedPlayoffs = null;

  @SerializedName("NumberOfPlayersToAdvance")
  private Integer numberOfPlayersToAdvance = null;

  @SerializedName("PlayRegularSeasonMatches")
  private Boolean playRegularSeasonMatches = null;

  public TournamentQualifierGroupModel groupNumber(Integer groupNumber) {
    this.groupNumber = groupNumber;
    return this;
  }

   /**
   * Get groupNumber
   * @return groupNumber
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getGroupNumber() {
    return groupNumber;
  }

  public void setGroupNumber(Integer groupNumber) {
    this.groupNumber = groupNumber;
  }

  public TournamentQualifierGroupModel groupName(String groupName) {
    this.groupName = groupName;
    return this;
  }

   /**
   * Get groupName
   * @return groupName
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getGroupName() {
    return groupName;
  }

  public void setGroupName(String groupName) {
    this.groupName = groupName;
  }

  public TournamentQualifierGroupModel isGuaranteedPlayoffs(Boolean isGuaranteedPlayoffs) {
    this.isGuaranteedPlayoffs = isGuaranteedPlayoffs;
    return this;
  }

   /**
   * Get isGuaranteedPlayoffs
   * @return isGuaranteedPlayoffs
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getIsGuaranteedPlayoffs() {
    return isGuaranteedPlayoffs;
  }

  public void setIsGuaranteedPlayoffs(Boolean isGuaranteedPlayoffs) {
    this.isGuaranteedPlayoffs = isGuaranteedPlayoffs;
  }

  public TournamentQualifierGroupModel numberOfPlayersToAdvance(Integer numberOfPlayersToAdvance) {
    this.numberOfPlayersToAdvance = numberOfPlayersToAdvance;
    return this;
  }

   /**
   * Get numberOfPlayersToAdvance
   * @return numberOfPlayersToAdvance
  **/
  @ApiModelProperty(example = "null", value = "")
  public Integer getNumberOfPlayersToAdvance() {
    return numberOfPlayersToAdvance;
  }

  public void setNumberOfPlayersToAdvance(Integer numberOfPlayersToAdvance) {
    this.numberOfPlayersToAdvance = numberOfPlayersToAdvance;
  }

  public TournamentQualifierGroupModel playRegularSeasonMatches(Boolean playRegularSeasonMatches) {
    this.playRegularSeasonMatches = playRegularSeasonMatches;
    return this;
  }

   /**
   * Get playRegularSeasonMatches
   * @return playRegularSeasonMatches
  **/
  @ApiModelProperty(example = "null", value = "")
  public Boolean getPlayRegularSeasonMatches() {
    return playRegularSeasonMatches;
  }

  public void setPlayRegularSeasonMatches(Boolean playRegularSeasonMatches) {
    this.playRegularSeasonMatches = playRegularSeasonMatches;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TournamentQualifierGroupModel tournamentQualifierGroupModel = (TournamentQualifierGroupModel) o;
    return Objects.equals(this.groupNumber, tournamentQualifierGroupModel.groupNumber) &&
        Objects.equals(this.groupName, tournamentQualifierGroupModel.groupName) &&
        Objects.equals(this.isGuaranteedPlayoffs, tournamentQualifierGroupModel.isGuaranteedPlayoffs) &&
        Objects.equals(this.numberOfPlayersToAdvance, tournamentQualifierGroupModel.numberOfPlayersToAdvance) &&
        Objects.equals(this.playRegularSeasonMatches, tournamentQualifierGroupModel.playRegularSeasonMatches);
  }

  @Override
  public int hashCode() {
    return Objects.hash(groupNumber, groupName, isGuaranteedPlayoffs, numberOfPlayersToAdvance, playRegularSeasonMatches);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TournamentQualifierGroupModel {\n");
    
    sb.append("    groupNumber: ").append(toIndentedString(groupNumber)).append("\n");
    sb.append("    groupName: ").append(toIndentedString(groupName)).append("\n");
    sb.append("    isGuaranteedPlayoffs: ").append(toIndentedString(isGuaranteedPlayoffs)).append("\n");
    sb.append("    numberOfPlayersToAdvance: ").append(toIndentedString(numberOfPlayersToAdvance)).append("\n");
    sb.append("    playRegularSeasonMatches: ").append(toIndentedString(playRegularSeasonMatches)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

