/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

/**
 * TournamentMatchAssistanceModel
 */
@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-12-02T00:05:30.138Z")
public class TournamentMatchAssistanceModel {
  @SerializedName("TournamentMatchAssistanceId")
  private Long tournamentMatchAssistanceId = null;

  @SerializedName("TournamentMatchId")
  private Long tournamentMatchId = null;

  @SerializedName("AssistanceRequestedById")
  private Long assistanceRequestedById = null;

  @SerializedName("AssistanceRequestedDateTime")
  private DateTime assistanceRequestedDateTime = null;

  @SerializedName("ResolvedById")
  private Long resolvedById = null;

  @SerializedName("ResolutionDateTime")
  private DateTime resolutionDateTime = null;

  @SerializedName("ResolutionComments")
  private String resolutionComments = null;

  public TournamentMatchAssistanceModel tournamentMatchAssistanceId(Long tournamentMatchAssistanceId) {
    this.tournamentMatchAssistanceId = tournamentMatchAssistanceId;
    return this;
  }

   /**
   * Get tournamentMatchAssistanceId
   * @return tournamentMatchAssistanceId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTournamentMatchAssistanceId() {
    return tournamentMatchAssistanceId;
  }

  public void setTournamentMatchAssistanceId(Long tournamentMatchAssistanceId) {
    this.tournamentMatchAssistanceId = tournamentMatchAssistanceId;
  }

  public TournamentMatchAssistanceModel tournamentMatchId(Long tournamentMatchId) {
    this.tournamentMatchId = tournamentMatchId;
    return this;
  }

   /**
   * Get tournamentMatchId
   * @return tournamentMatchId
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getTournamentMatchId() {
    return tournamentMatchId;
  }

  public void setTournamentMatchId(Long tournamentMatchId) {
    this.tournamentMatchId = tournamentMatchId;
  }

  public TournamentMatchAssistanceModel assistanceRequestedById(Long assistanceRequestedById) {
    this.assistanceRequestedById = assistanceRequestedById;
    return this;
  }

   /**
   * Get assistanceRequestedById
   * @return assistanceRequestedById
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getAssistanceRequestedById() {
    return assistanceRequestedById;
  }

  public void setAssistanceRequestedById(Long assistanceRequestedById) {
    this.assistanceRequestedById = assistanceRequestedById;
  }

  public TournamentMatchAssistanceModel assistanceRequestedDateTime(DateTime assistanceRequestedDateTime) {
    this.assistanceRequestedDateTime = assistanceRequestedDateTime;
    return this;
  }

   /**
   * Get assistanceRequestedDateTime
   * @return assistanceRequestedDateTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getAssistanceRequestedDateTime() {
    return assistanceRequestedDateTime;
  }

  public void setAssistanceRequestedDateTime(DateTime assistanceRequestedDateTime) {
    this.assistanceRequestedDateTime = assistanceRequestedDateTime;
  }

  public TournamentMatchAssistanceModel resolvedById(Long resolvedById) {
    this.resolvedById = resolvedById;
    return this;
  }

   /**
   * Get resolvedById
   * @return resolvedById
  **/
  @ApiModelProperty(example = "null", value = "")
  public Long getResolvedById() {
    return resolvedById;
  }

  public void setResolvedById(Long resolvedById) {
    this.resolvedById = resolvedById;
  }

  public TournamentMatchAssistanceModel resolutionDateTime(DateTime resolutionDateTime) {
    this.resolutionDateTime = resolutionDateTime;
    return this;
  }

   /**
   * Get resolutionDateTime
   * @return resolutionDateTime
  **/
  @ApiModelProperty(example = "null", value = "")
  public DateTime getResolutionDateTime() {
    return resolutionDateTime;
  }

  public void setResolutionDateTime(DateTime resolutionDateTime) {
    this.resolutionDateTime = resolutionDateTime;
  }

  public TournamentMatchAssistanceModel resolutionComments(String resolutionComments) {
    this.resolutionComments = resolutionComments;
    return this;
  }

   /**
   * Get resolutionComments
   * @return resolutionComments
  **/
  @ApiModelProperty(example = "null", value = "")
  public String getResolutionComments() {
    return resolutionComments;
  }

  public void setResolutionComments(String resolutionComments) {
    this.resolutionComments = resolutionComments;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TournamentMatchAssistanceModel tournamentMatchAssistanceModel = (TournamentMatchAssistanceModel) o;
    return Objects.equals(this.tournamentMatchAssistanceId, tournamentMatchAssistanceModel.tournamentMatchAssistanceId) &&
        Objects.equals(this.tournamentMatchId, tournamentMatchAssistanceModel.tournamentMatchId) &&
        Objects.equals(this.assistanceRequestedById, tournamentMatchAssistanceModel.assistanceRequestedById) &&
        Objects.equals(this.assistanceRequestedDateTime, tournamentMatchAssistanceModel.assistanceRequestedDateTime) &&
        Objects.equals(this.resolvedById, tournamentMatchAssistanceModel.resolvedById) &&
        Objects.equals(this.resolutionDateTime, tournamentMatchAssistanceModel.resolutionDateTime) &&
        Objects.equals(this.resolutionComments, tournamentMatchAssistanceModel.resolutionComments);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tournamentMatchAssistanceId, tournamentMatchId, assistanceRequestedById, assistanceRequestedDateTime, resolvedById, resolutionDateTime, resolutionComments);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TournamentMatchAssistanceModel {\n");
    
    sb.append("    tournamentMatchAssistanceId: ").append(toIndentedString(tournamentMatchAssistanceId)).append("\n");
    sb.append("    tournamentMatchId: ").append(toIndentedString(tournamentMatchId)).append("\n");
    sb.append("    assistanceRequestedById: ").append(toIndentedString(assistanceRequestedById)).append("\n");
    sb.append("    assistanceRequestedDateTime: ").append(toIndentedString(assistanceRequestedDateTime)).append("\n");
    sb.append("    resolvedById: ").append(toIndentedString(resolvedById)).append("\n");
    sb.append("    resolutionDateTime: ").append(toIndentedString(resolutionDateTime)).append("\n");
    sb.append("    resolutionComments: ").append(toIndentedString(resolutionComments)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

