/*
 * Polling API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ResponseOutputModelMaintenanceModeModel;
import io.swagger.client.model.ResponseOutputModelCommsModel;
import io.swagger.client.model.ResponseOutputModelSynchronizationTimeModel;
import org.junit.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PlatformControlEndpointApi
 */
public class PlatformControlEndpointApiTest {

    private final PlatformControlEndpointApi api = new PlatformControlEndpointApi();

    
    /**
     * Get the status of maintenance mode for the platform
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void platformMaintenanceStatusTest() throws ApiException {
        String lastUpdatedDateTime = null;
        // ResponseOutputModelMaintenanceModeModel response = api.platformMaintenanceStatus(lastUpdatedDateTime);

        // TODO: test validations
    }
    
    /**
     * Get the installed version of Razer comms for the logged in player
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void platformRazerCommsVersionTest() throws ApiException {
        // ResponseOutputModelCommsModel response = api.platformRazerCommsVersion();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void platformTimeSynchronizationTest() throws ApiException {
        String clientTime = null;
        // ResponseOutputModelSynchronizationTimeModel response = api.platformTimeSynchronization(clientTime);

        // TODO: test validations
    }
    
}
